<?php
/**
 * Implements hook_node_view().
 *
 * Adds a Facebook like button to page nodes.
 */
function product_extend_node_view($node, $view_mode, $langcode) {
    switch ($node->type) {
        case 'tour':
            $node->content['product_extend_cart_add'] = array(
                '#type' => 'item',
                '#title' => '',
                //'#markup' => '<a href="'.url('ajax/product/cart/push',array('query' => array('nid' => $node->nid))).'">'.t('Demande de devis').'</a>',
                '#markup' => '<a class="btn-product-cart" data-pid="'.$node->nid.'" href="javascript: void(0);">'.t('Đặt Tour').'</a>',
            );

            $node->content['product_title'] = array(
                '#type' => 'item',
                '#title' => '',
                '#markup' =>  '<h1>'.$node->title.'</h1>',
            );
            break;

            break;
    }
}

/**
 * Implements hook_field_extra_fields().
 *
 * Declare our Facebook Like button as a pseudo-field.
 */
function product_extend_field_extra_fields() {
    $extra['node']['tour']['display'] = array(

        'product_extend_cart_add' => array(
            'label' => t('Add to cart'),
            'description' => t('Add to cart button.'),
            'weight' => 11,
        ),
        'product_title' => array(
            'label' => t('Title'),
            'description' => t('Title.'),
            'weight' => 12,
        )
    );
    return $extra;
}

/**
 * Implements hook_theme().
 */
function product_extend_theme() {
    return array(
        'product_extend_link' => array(
            'variables' => array(
                'item_list' => NULL,
            ),
            'template' => 'templates/product-extend-link',
        ),
        'product_mobile_action' => array(
            'variables' => array(
                'node' => NULL,
            ),
            'template' => 'templates/product-mobile-action',
        ),
    );
}